[package]
name = "rtcl_tp25k_usb3_fifo_sample"
version = "0.1.0"
edition = "2024"

[dependencies]
d3xx = "0.0.3"
jelly-mem_access = { version="0.2.7" }
jelly-pac = { version="0.1.2" }
jelly-lib = { version="0.2.2" }

# jelly-pac = { git="https://github.com/ryuz/jelly-pac.git", rev="c8daa82" }
# jelly-lib = { git="https://github.com/ryuz/jelly-lib.git", rev="4685606" }
