create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_design_1/clk_wiz_0/inst/clk_out3]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {mon_frame_rate_value[0]} {mon_frame_rate_value[1]} {mon_frame_rate_value[2]} {mon_frame_rate_value[3]} {mon_frame_rate_value[4]} {mon_frame_rate_value[5]} {mon_frame_rate_value[6]} {mon_frame_rate_value[7]} {mon_frame_rate_value[8]} {mon_frame_rate_value[9]} {mon_frame_rate_value[10]} {mon_frame_rate_value[11]} {mon_frame_rate_value[12]} {mon_frame_rate_value[13]} {mon_frame_rate_value[14]} {mon_frame_rate_value[15]} {mon_frame_rate_value[16]} {mon_frame_rate_value[17]} {mon_frame_rate_value[18]} {mon_frame_rate_value[19]} {mon_frame_rate_value[20]} {mon_frame_rate_value[21]} {mon_frame_rate_value[22]} {mon_frame_rate_value[23]} {mon_frame_rate_value[24]} {mon_frame_rate_value[25]} {mon_frame_rate_value[26]} {mon_frame_rate_value[27]} {mon_frame_rate_value[28]} {mon_frame_rate_value[29]} {mon_frame_rate_value[30]} {mon_frame_rate_value[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {mon_frame_count[0]} {mon_frame_count[1]} {mon_frame_count[2]} {mon_frame_count[3]} {mon_frame_count[4]} {mon_frame_count[5]} {mon_frame_count[6]} {mon_frame_count[7]} {mon_frame_count[8]} {mon_frame_count[9]} {mon_frame_count[10]} {mon_frame_count[11]} {mon_frame_count[12]} {mon_frame_count[13]} {mon_frame_count[14]} {mon_frame_count[15]} {mon_frame_count[16]} {mon_frame_count[17]} {mon_frame_count[18]} {mon_frame_count[19]} {mon_frame_count[20]} {mon_frame_count[21]} {mon_frame_count[22]} {mon_frame_count[23]} {mon_frame_count[24]} {mon_frame_count[25]} {mon_frame_count[26]} {mon_frame_count[27]} {mon_frame_count[28]} {mon_frame_count[29]} {mon_frame_count[30]} {mon_frame_count[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {mon_frame_rate_count[0]} {mon_frame_rate_count[1]} {mon_frame_rate_count[2]} {mon_frame_rate_count[3]} {mon_frame_rate_count[4]} {mon_frame_rate_count[5]} {mon_frame_rate_count[6]} {mon_frame_rate_count[7]} {mon_frame_rate_count[8]} {mon_frame_rate_count[9]} {mon_frame_rate_count[10]} {mon_frame_rate_count[11]} {mon_frame_rate_count[12]} {mon_frame_rate_count[13]} {mon_frame_rate_count[14]} {mon_frame_rate_count[15]} {mon_frame_rate_count[16]} {mon_frame_rate_count[17]} {mon_frame_rate_count[18]} {mon_frame_rate_count[19]} {mon_frame_rate_count[20]} {mon_frame_rate_count[21]} {mon_frame_rate_count[22]} {mon_frame_rate_count[23]} {mon_frame_rate_count[24]} {mon_frame_rate_count[25]} {mon_frame_rate_count[26]} {mon_frame_rate_count[27]} {mon_frame_rate_count[28]} {mon_frame_rate_count[29]} {mon_frame_rate_count[30]} {mon_frame_rate_count[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk250]
