

# MIPI
# set_property INTERNAL_VREF 0.6 [get_iobanks 35]
# set_property PACKAGE_PIN H18 [get_ports cam_clk_hs_n]
# set_property PACKAGE_PIN J18 [get_ports cam_clk_hs_p]
# set_property PACKAGE_PIN M20 [get_ports {cam_data_hs_n[0]}]
# set_property PACKAGE_PIN M19 [get_ports {cam_data_hs_p[0]}]
# set_property PACKAGE_PIN L17 [get_ports {cam_data_hs_n[1]}]
# set_property PACKAGE_PIN L16 [get_ports {cam_data_hs_p[1]}]
# set_property PACKAGE_PIN H20 [get_ports cam_clk_lp_p]
# set_property PACKAGE_PIN J19 [get_ports cam_clk_lp_n]
# set_property PACKAGE_PIN L19 [get_ports {cam_data_lp_p[0]}]
# set_property PACKAGE_PIN M18 [get_ports {cam_data_lp_n[0]}]
# set_property PACKAGE_PIN J20 [get_ports {cam_data_lp_p[1]}]
# set_property PACKAGE_PIN L20 [get_ports {cam_data_lp_n[1]}]
set_property PACKAGE_PIN G20 [get_ports cam_gpio0]
#set_property PACKAGE_PIN G19 [get_ports cam_gpio1]
set_property PACKAGE_PIN F20 [get_ports cam_scl]
set_property PACKAGE_PIN F19 [get_ports cam_sda]

# set_property IOSTANDARD LVDS_25 [get_ports cam_clk_hs_p]
# set_property IOSTANDARD LVDS_25 [get_ports cam_clk_hs_n]
# set_property IOSTANDARD LVDS_25 [get_ports {cam_data_hs_p[0]}]
# set_property IOSTANDARD LVDS_25 [get_ports {cam_data_hs_n[0]}]
# set_property IOSTANDARD LVDS_25 [get_ports {cam_data_hs_p[1]}]
# set_property IOSTANDARD LVDS_25 [get_ports {cam_data_hs_n[1]}]
# set_property IOSTANDARD HSUL_12 [get_ports cam_clk_lp_p]
# set_property IOSTANDARD HSUL_12 [get_ports cam_clk_lp_n]
# set_property IOSTANDARD HSUL_12 [get_ports {cam_data_lp_p[0]}]
# set_property IOSTANDARD HSUL_12 [get_ports {cam_data_lp_n[0]}]
# set_property IOSTANDARD HSUL_12 [get_ports {cam_data_lp_p[1]}]
# set_property IOSTANDARD HSUL_12 [get_ports {cam_data_lp_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports cam_gpio0]
# set_property IOSTANDARD LVCMOS33 [get_ports cam_gpio1]
set_property IOSTANDARD LVCMOS33 [get_ports cam_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cam_sda]
